name: Publish Docker image for new releases

on:
  push:
    branches: [ workshop ]
  pull_request:
    branches: [ workshop ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          
      - name: Build and push
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: scripts/Dockerfile
          tags: |
            onfinality/acala:${{ steps.vars.outputs.sha_short }}
            
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      - name: Update image version of the new network spec 
      
        uses: "OnFinality-io/action-onf-release@v1"
        with:
          onf-access-key: "gAuUEFx1NTWBt22uUHcrgzJYJ9rs70oj"
          onf-secret-key: "oOn+MYnk0ZUYGPjq1w6DhWBUhVYRHBc96J8brAfc"
          onf-workspace-id: "6683212593101979648"
          onf-network-key: 6cfd4157-75f5-4eca-a6fa-a57ec176f217 
          onf-sub-command: image # node, image
          onf-action: add # upgrade, add
          image-version: ${{ steps.vars.outputs.sha_short }}
          
      - name: Perform a rolling update to all nodes
        uses: "OnFinality-io/action-onf-release@v1"
        with:
          onf-access-key: "gAuUEFx1NTWBt22uUHcrgzJYJ9rs70oj"
          onf-secret-key: "oOn+MYnk0ZUYGPjq1w6DhWBUhVYRHBc96J8brAfc"
          onf-workspace-id: "6683212593101979648"
          onf-network-key: 6cfd4157-75f5-4eca-a6fa-a57ec176f217 
          onf-sub-command: node # node, image
          onf-action: upgrade # upgrade, add
          image-version: ${{ steps.vars.outputs.sha_short }}
          percent: 30
